gui:
  theme:
    activeBorderColor:
      - "#7e9cd8"
    inactiveBorderColor:
      - "#dcd7ba"
    searchingActiveBorderColor:
      - "#7fb4ca"
    optionsTextColor:
      - "#c8c093"
    selectedLineBgColor:
      - "#2d4f67"
    inactiveViewSelectedLineBgColor:
      - "#3f6b88"
    cherryPickedCommitFgColor:
      - "#dcd7ba"
    cherryPickedCommitBgColor:
      - "#c34043"
    unstagedChangesColor:
      - "#727169"

  authorColors:
    "John Ide": "#7e9cd8"
    "*": "#c8c093"

  branchColorPatterns:
    "^master$": "#7e9cd8"
    "^main$": "#7e9cd8"
    "^mainline$": "#7e9cd8"
    "^release-*": "#7e9cd8"

  showNumstatInFilesView: true

  showRandomTip: false

  showCommandLog: false

  showBottomLine: false

  showPanelJumps: false

  nerdFontsVersion: "3"

  border: rounded

  skipDiscardChangeWarning: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  mainBranches:
    - master
    - main
    - mainline

  skipHookPrefix: wip

  branchLogCmd: git log --color --abbrev-commit --show-signature --date=local --graph

  parseEmoji: true

update:
  method: background

refresher:
  refreshInterval: 3

keybinding:
  universal:
    quit: q
    return: <esc>
    togglePanel: <tab>
    prevItem: k
    nextItem: j
    prevPage: <c-p>
    nextPage: <c-n>
    scrollLeft: h
    scrollRight: l
    gotoTop: <disabled>
    gotoBottom: <disabled>
    toggleRangeSelect: v
    prevBlock: h
    nextBlock: l
    nextMatch: n
    prevMatch: N
    startSearch: /
    optionMenu: "?"
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirmInEditor: <a-enter>
    remove: d
    new: n
    scrollUpMain: <c-p>
    scrollDownMain: <c-n>
    executeShellCommand: ":"
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: +
    prevScreenMode: _
    undo: u
    redo: <c-r>
    filteringMenu: <c-s>
    diffingMenu: W
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    increaseRenameSimilarityThreshold: )
    decreaseRenameSimilarityThreshold: (
    openDiffTool: <c-t>
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraph: a
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    findBaseCommitForFixup: <c-f>
    confirmDiscard: x
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: "`"
    openMergeTool: M
    openStatusFilter: <c-b>
    copyFileInfoToClipboard: y
    collapseAll: "-"
    expandAll: =
  branches:
    # createPullRequest: o
    # viewPullRequestOptions: O
    # copyPullRequestURL: <c-y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    rebaseBranch: r
    renameBranch: R
    mergeIntoCurrentBranch: M
    viewGitFlowOptions: i
    fastForward: f
    createTag: T
    pushTag: P
    setUpstream: u
    fetchRemote: f
    sortOrder: s
  worktrees:
    viewWorktreeOptions: w
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: g
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: <c-j>
    moveUpCommit: <c-k>
    amendToCommit: A
    resetCommitAuthor: a
    pickCommit: p
    revertCommit: t
    cherryPickCopy: C
    pasteCommits: V
    markCommitAsBaseForRebase: B
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <c-R>
    copyCommitAttributeToClipboard: "y"
    openLogMenu: <c-l>
    openInBrowser: o
    viewBisectOptions: b
    startInteractiveRebase: i
  amendAttribute:
    resetAuthor: a
    setAuthor: A
    addCoAuthor: c
  stash:
    popStash: g
    renameStash: r
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleSelectHunk: a
    pickBothHunks: b
    editSelectHunk: E
  submodules:
    init: i
    update: u
    bulkMenu: b
  commitMessage:
    commitMenu: <c-o>

customCommands:
  - key: o
    description: Open or update a CR
    context: localBranches,files,commits
    prompts:
      - type: input
        title: Enter the URL of an existing revision (if applicable)
        key: ExistingRevision
      - type: input
        title: Enter the name of the destination branch
        key: DestinationBranch
        initialValue: mainline
        suggestions:
          preset: branches
    command: "cr {{if .Form.ExistingRevision}} --update-review {{.Form.ExistingRevision}} {{else}} --new-review {{end}} --parent $(git parent) --destination-branch {{.Form.DestinationBranch}}"
    loadingText: "Creating CR revision"
    showOutput: true
    outputTitle: CR
