gui:
  authorColors:
    "John Ide": "#7e9cd8"

  branchColorPatterns:
    "^master$": "#7e9cd8"
    "^main$": "#7e9cd8"
    "^mainline$": "#7e9cd8"
    "^release-*": "#7e9cd8"
    "^dev$*": "#7e9cd8"
    "^staging$*": "#7e9cd8"

  skipDiscardChangeWarning: true

  theme:
    activeBorderColor:
      - "#7e9cd8"
    inactiveBorderColor:
      - "#dcd7ba"
    searchingActiveBorderColor:
      - "#7fb4ca"
    optionsTextColor:
      - "#c8c093"
    selectedLineBgColor:
      - "#2d4f67"
    inactiveViewSelectedLineBgColor:
      - "#3f6b88"
    cherryPickedCommitFgColor:
      - "#dcd7ba"
    cherryPickedCommitBgColor:
      - "#c34043"
    unstagedChangesColor:
      - "#727169"

  showNumstatInFilesView: true

  showRandomTip: false

  showCommandLog: false

  showBottomLine: false

  showPanelJumps: false

  nerdFontsVersion: "3"

  showDivergenceFromBaseBranch: arrowAndNumber

  commandLogSize: 30

  filterMode: fuzzy

  skipSwitchWorktreeOnCheckoutWarning: true

os:
  editInTerminal: false
  edit: 'nvim --server "$NVIM" --remote-send "<C-\\><C-n>:close | edit {{filename}}<CR>"'
  editAtLine: 'nvim --server "$NVIM" --remote-send "<C-\\><C-n>:close | edit +{{line}} {{filename}} | normal! zz<CR>"'

git:
  pagers:
    - pager: delta --paging=never

  mainBranches:
    - master
    - main
    - mainline

  skipHookPrefix: wip

  autoForwardBranches: allBranches

  branchLogCmd: 'git log --graph --color=always --abbrev-commit --date=format-local:"%-I:%M %p %Z - %a, %b %-d %Y" --pretty=format:"%C(yellow)%h%C(reset)%n%C(blue)Author: %an <%ae>%C(reset)%C(green) %GK%C(reset)%n%C(#c8c093)%ar (%ad)%C(reset)%n%n  %s%n%b%N" --'

  overrideGpg: true

  parseEmoji: true

  localBranchSortOrder: recency

refresher:
  refreshInterval: 2

customCommands:
  - key: o
    command: "cr {{if .Form.ExistingRevision}} --update-review {{.Form.ExistingRevision}} {{else}} --new-review {{end}} --parent $(git parent) --destination-branch {{.Form.DestinationBranch}}"
    context: localBranches
    prompts:
      - type: input
        title: Enter the URL of an existing revision (if applicable)
        key: ExistingRevision
      - type: input
        title: Enter the name of the destination branch
        key: DestinationBranch
        initialValue: mainline
        suggestions:
          preset: branches
    loadingText: "Creating CR revision"
    description: Open or update a CR
    output: popup
    outputTitle: CR

services:
  ssh.code.aws.dev: gitlab:code.aws.dev

keybinding:
  universal:
    prevItem: k
    nextItem: j
    scrollLeft: h
    scrollRight: l
    prevBlock: h
    nextBlock: l
    optionMenu: "?"
    undo: u
    redo: <c-r>
